### ISSUE TITLE
Redirect Loop after Submitting Password Expired 

### ISSUE THREAD

**Issue by brunzino** [phatworx/devise_security_extension#101]
After successfully changing a password for because it was expired, a redirect loop happens because the warden session does not get updated correctly. In `/app/controllers/devise/password_expired_controller.rb` the warden session variable `warden.session(scope)['password_expired']` is set to true. When the password is successfully updated, the warden session variable `warden.session(scope)[:password_expired]` is set to false - setting with the key as symbol :password_expired instead of the convention of the string 'password_expired'.

I've forked and committed the fix, will submit a pull request

**Comment by stringsn88keys** [comment]
Handled in PR https://github.com/phatworx/devise_security_extension/pull/110
