### ISSUE TITLE
Updated gemspec creates a circular dependency 

### ISSUE THREAD

**Issue by seanknox** [phatworx/devise_security_extension#113]
Running `bundle` with the latest commit: 

```
Your Gemfile requires gems that depend on each other, creating an infinite loop. Please
remove gem 'devise_security_extension' and try again.
```

**Comment by seanknox** [comment]
Caused by this commit: https://github.com/phatworx/devise_security_extension/commit/5ac50f21806bd6440d8a18641d64e7fc7d4258fd

**Comment by yhjor1212** [comment]
I have this problem too. Please fix it thanks!

**Comment by seanknox** [comment]
In the meantime, you can pin your version to the SHA before this one in
your Gemfile.

**Comment by stringsn88keys** [comment]
I'm looking into it. Having a bit of trouble reproducing in my environment to verify.

**Comment by codezomb** [comment]
Definitely seeing this as well.

**Comment by brokenladder** [comment]
This clearly creates a self-dependency.

```bash
gem dependency devise_security_extension -v 0.8.1 --reverse-dependencies
Gem devise_security_extension-0.8.1
  bundler (>= 1.0.0, development)
  devise (>= 2.0.0)
  devise_security_extension (>= 0)
  easy_captcha (>= 0, development)
  jeweler (~> 2.0.1, development)
  rails (>= 3.1.1)
  rails_email_validator (>= 0, development)
  sqlite3 (>= 0, development)
  Used by
    devise_security_extension-0.8.1 (devise_security_extension (>= 0))
```

**Comment by stringsn88keys** [comment]
Ok. Merged the PR above and manually did gem tasks. Can anyone else verify that `0.8.3` works for them now?
