### ISSUE TITLE
Open to writing new and old specs with RSpec?

### ISSUE THREAD

**Issue by seanknox** [phatworx/devise_security_extension#118]
Hi, `devise_security_extension` is a gem I use in a number of projects and I'd like to improve test coverage. Would you be open to a PR switching from `Test::Unit` to RSpec? I think it will lend itself to increased tests as well as clearer descriptions of what is being tested. Wanted to have your buy in before submitting a PR. 

Additionally, Rubydocs recommends using test frameworks other than `Test::Unit`—it's only in the standard library for legacy reasons, and is removed from stdlib starting in version 2.2.0.

**Comment by seanknox** [comment]
@traxanos @stringsn88keys

**Comment by traxanos** [comment]
do you want to replace all (old) tests to rspec? i think the idea good, but i didn't have time at the moment to support.

fyi: @equivalent

**Comment by stringsn88keys** [comment]
I'd love to. Getting a really slow start on adding testing.

Thanks,
Thomas

**Comment by seanknox** [comment]
Awesome. I have a PR I'm about to submit that provides Rubocop, has some code cleanup, enables existing tests that were disabled, and adds a test for the initializer generator. Once that gets the thumbs up, I'll start new work on moving things to RSpec.

**Comment by equivalent** [comment]
+1 for RSpec :)
