### ISSUE TITLE
CHANGELOG.md

### ISSUE THREAD

**Issue by locochris** [phatworx/devise_security_extension#126]
ie. so we can figure out what's changed.  :smile:

And FYI, the releases published in:
 * https://rubygems.org/gems/devise_security_extension/versions

don't match the releases tagged in:
 * https://github.com/phatworx/devise_security_extension/releases

One says the latest version is `v0.9.2`, while the other `v0.8.2`.
(perhaps something happened aroung the 270b67aff5ec5d6cc4584abab02171e9a84b3546 commit?)

**Comment by tcostermans** [comment]
+1, git tags are missing from v0.8.2 while v0.9.2 is available on https://rubygems.org/gems/devise_security_extension

**Comment by traxanos** [comment]
at the moment the version 9 is a git version and not published.

**Comment by traxanos** [comment]
oh, ok i see what you mean. correct the git tag is missing. i didn't push it, so i didn't know the correct hash.

**Comment by monfresh** [comment]
Please consider reopening and addressing the original intent of this issue, which is to maintain a CHANGELOG.md file that will list all the changes that went into each release. [github-changelog-generator](https://github.com/skywinder/github-changelog-generator) is an awesome tool that can automatically do that for you. All you have to do is install the gem, run `github_changelog_generator`, and it will go through all your releases and generate a wonderful CHANGELOG, like this one: https://github.com/codeforamerica/ohana-api/blob/master/CHANGELOG.md
