### ISSUE TITLE
How to install last version of devise_security_extension

### ISSUE THREAD

**Issue by Elyahou** [phatworx/devise_security_extension#143]
When Installing with gem, we don't get the last version of Master branch.

I need the changes in password_salt that are in master, it it possible to publish the new version ?

Thank you

**Comment by chrisgogreen** [comment]
This would help me also.

**Comment by zxr90** [comment]
specify this in your gemfile
```ruby
gem 'devise_security_extension', github: 'phatworx/devise_security_extension'
```
