### ISSUE TITLE
Help me use this gem

### ISSUE THREAD

**Issue by dtognazzini** [phatworx/devise_security_extension#152]
I and my company would love to use this gem. But there are a few things that are keeping us from being able to.

1. Is this gem ready for general use? According to [semver](http://semver.org/spec/v2.0.0.html):
> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

  The currently released version of this gem is 0.9.2. Can we depend on the public API being stable? Is there a plan to adopt semver?

2. It seems like there are a few maintainers of this gem, which is something we look for before adopting gems. Is the plan to keep this gem up to date with future versions of Rails and devise?

3. One thing that I'm confused about is the release process. The [code currently has 0.10.0](https://github.com/phatworx/devise_security_extension/blob/6fbf95fb262135584c1dae7a7756867c95a69752/lib/devise_security_extension/version.rb#L2) as the version number, but there is no 0.10.0 release on rubygems. We need a version released with the fix in commit https://github.com/phatworx/devise_security_extension/commit/a633e5e71cd7222c3cbd2d3dc92455ccd0554191.

  Typically we find that gem authors use git tags for releases. It looks like that was the practice for this gem up to 0.8.2: https://github.com/phatworx/devise_security_extension/tags

  We use these tags to compare the contents of the gem across versions. For example:
https://github.com/phatworx/devise_security_extension/compare/v0.8.1...v0.8.2

  Rubygems shows releases for versions 0.8.3, 0.8.4, 0.9.1, 0.9.2 but there are no corresponding tags in the Github repository.

4. The `DeviseSecurityExtension::Controllers::Helpers` module is mixed into `ActionController::Base` [by `DeviseSecurityExtension::Engine`](https://github.com/phatworx/devise_security_extension/blob/6fbf95fb262135584c1dae7a7756867c95a69752/lib/devise_security_extension/rails.rb#L4
). This module seems to be only necessary for the password_expirable and paranoid_verification modules. We are not using those modules and since there isn't a release for #146, we are having to monkey patch this gem for these features. It would be better for us if this module were only mixed in when either of those modules are enabled.

5. Lastly, our application is rather large and we've chosen to use https://github.com/rails/protected_attributes when we upgraded to Rails 4. The use of rails/protected_attributes causes errors with the PasswordArchivable module [here](https://github.com/phatworx/devise_security_extension/blob/6fbf95fb262135584c1dae7a7756867c95a69752/lib/devise_security_extension/models/password_archivable.rb#L30).

  We've had to monkey patch the model to turn off mass assignment checks. 

Thanks for maintaining this gem! We would love to use it.

**Comment by traxanos** [comment]
Hi 

I have at the moment not enough time.
U are interesst to maintain this gem?

Greets marco 

Von meinem iPhone gesendet

**Comment by manno** [comment]
I think the answer to 4. is to split this gem into separate gems for each module.

With regards to 5.: I think extending the existing classes is the right way if you're using the protected_attributes gem.

I'm closing this ticket.
