### ISSUE TITLE
README.md and gem out of sync for Password archivable

### ISSUE THREAD

**Issue by evanwang22** [phatworx/devise_security_extension#160]
Commit 77708b33c724ac313fbb044a800572759c4b0335 changes Password Archivable to remove the `:password_salt` attribute from `old_passwords`. This is reflected in the README.md, but the latest release of the gem (0.9.2) doesn't include this change, so following the README resulted in an ActiveRecord error:

`ActiveRecord::UnknownAttributeError: unknown attribute 'password_salt' for OldPassword.`

**Comment by hallmatt** [comment]
@evanwang22 I'm getting the same issue. Were you able to find a workaround?

**Comment by manno** [comment]
Does the new gem fix this issue?
