### ISSUE TITLE
Deprecation Warning: to_prepare

### ISSUE THREAD

**Issue by hallmatt** [phatworx/devise_security_extension#169]
I'm using the latest version of Rails 5 beta 3 and am receiving this error:

```ruby
DEPRECATION WARNING: to_prepare is deprecated and will be removed from Rails 5.1 (use 
ActiveSupport::Reloader.to_prepare instead). (called from <class:Engine> at 
/Users/USER/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/devise_security_extension-
0.10.0/lib/devise_security_extension/rails.rb:7)
```

I'm on version 0.10.0 of the gem.

**Comment by levi-l-damian** [comment]
I am using Rails 5.0.0. and I am getting the same warning. 
Can't use the fix using the lib/ has no devise_security_extension/rails.rb

**Comment by krtschmr** [comment]
still applies

gem 'devise_security_extension'



$ rails c
DEPRECATION WARNING: to_prepare is deprecated and will be removed from Rails 5.1 (use ActiveSupport::Reloader.to_prepare instead) (called from <top (required)> at /home/tim/rails/modhoster/config/application.rb:7)
Loading development environment (Rails 5.0.1)

**Comment by ChunAllen** [comment]
I'm using `Rails 5.0.2` and device_security_extension `0.10.0`

I still get this: 

```
DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead. (called from <top (required)> 
DEPRECATION WARNING: to_prepare is deprecated and will be removed from Rails 5.1 (use ActiveSupport::Reloader.to_prepare instead) (called from <top (required)>
DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead. (called from <top (required)>
```
