### ISSUE TITLE
Devise 4.0 support

### ISSUE THREAD

**Issue by spdawson** [phatworx/devise_security_extension#178]
The gemspec currently locks the Devise version at `< 4.0`; is that a hard requirement, or could it be weakened to allow this gem to work with Devise 4.0?

**Comment by atarantino** [comment]
Same concerns here.

Originally was using 0.9.2 and was working with Devise 4.0.
After updating to 0.10.0 it knocked down Devise to 3.5.9.

**Comment by knightq** [comment]
👍

**Comment by rbclark** [comment]
Looks like this was changed in commit 8a9e871 with no explanation as to the exact reason. Looks like it may have just been a mistake but it may be best to hear from the person who performed that commit to know for sure.

**Comment by manno** [comment]
@alexdreher @traxanos could you release a new gem?

**Comment by mathieujobin** [comment]
This can be closed now

**Comment by dmz006** [comment]
This is closed but it is still an issue.  
   devise_security_extension was resolved to 0.10.0, which depends on
      devise (< 4.0, >= 3.0.0)

**Comment by atarantino** [comment]
@dmz006 this is what I've been doing:
`gem 'devise_security_extension', github: 'phatworx/devise_security_extension`

bonus tip: place this at the top of your Gemfile to make sure you are retrieving gems through https
```
git_source(:github) do |repos_name|
  repos_name = "#{repos_name}/#{repos_name}" unless repos_name.include?("/")
  "https://github.com/#{repos_name}.git"
end
```

**Comment by mathieujobin** [comment]
@dmz006 because a gem was not released. but it's fix on github. sorry about that

@atarantino i don't need a custom `git_source` for it.

for me `gem 'devise_security_extension', github: 'phatworx/devise_security_extension` works out of the box, if I want to explicitly use https, I do..

`gem 'devise_security_extension', git: 'https://github.com/phatworx/devise_security_extension.git'`

but I never want such a thing ;)

**Comment by fonji** [comment]
You may need to use it one day, as some production servers can't access the github using the git:// protocol. Also, https is more secure.

For a global setting on a single machine, you could also use
`git config --global url."https://github.com".insteadOf git://github.com`
which allows you to continue using git:// on other machines / stages.
