### ISSUE TITLE
still maintained?

### ISSUE THREAD

**Issue by mathieujobin** [phatworx/devise_security_extension#233]
would you be willing to transfer ownership?
I find it sad to see this gem being forked under a different name and all of these PR left unreviewed/unmerged.

within the authors of those recent PR there must be a couple kind enough to step up as a maintainer....

I have limited time but I am willing to at least merge the obvious one and push a release to rubygems

should I be given the right to

cheers

**Comment by maxexcloo** [comment]
Which forks are there?

**Comment by mathieujobin** [comment]
https://github.com/devise-security/devise-security seems to be the best effort. they are responsive at least

**Comment by mathieujobin** [comment]
no longer interested, thank you
