### ISSUE TITLE
OldPassword Assumes password_salt exists

### ISSUE THREAD

**Issue by vizjerai** [phatworx/devise_security_extension#45]
I'm using devise with bcrypt and it doesn't need a password_salt so I removed it along with the one in old_passwords table in 0.6.0 and ```attr_accessible :password_salt``` was added to ```OldPassword``` in 0.6.2

It would be nice if there was a way to work around it by defining my own OldPassword class or some config to specify the accessible attributes.

**Comment by dzajic** [comment]
I think the code should not assume :password_salt exists. This change solves it for me:

      def old_password_params
        old_params = { :encrypted_password => self.encrypted_password_change.first }
        salt_change = if self.respond_to?(:password_salt_change) and not self.password_salt_change.nil?
          params[:password_salt] = self.password_salt_change.first
        end
        old_params
      end

**Comment by dzajic** [comment]
I think the code should not assume :password_salt exists. This change solved it for me:

      def old_password_params
        old_params = { :encrypted_password => self.encrypted_password_change.first }
        salt_change = if self.respond_to?(:password_salt_change) and not self.password_salt_change.nil?
          params[:password_salt] = self.password_salt_change.first
        end
        old_params
      end

**Comment by manno** [comment]
Since password_salt was removed in Commit 77708b3 I believe this is no longer an issue.
