### ISSUE TITLE
password_expirable just doesn't work on v0.8.0

### ISSUE THREAD

**Issue by alfredorico** [phatworx/devise_security_extension#83]
Greettings,

Do any of you have had problems with password_expirable module? I'm using 0.8.0 and just doesn't work.
I have created a new user with column password_changed_at with 10.years.ago as follows

u = User.create(login: 'sistema', nombre_usuario: 'sistema', email: 'sistema_base@logmailplus.net', password: 'Aa98762ridi', password_changed_at: 10.years.ago )

Then after authenticate (user/sign_in) I would expect to be redirected to password_expirable funcionality but nothing happens, simply my root_path it's loaded.

I have previously used devise_security_extension v0.4.2 with rails 3.1 and everything works fine.  Now I'm on Rails 4.1.1.

Any suggests?..

**Comment by stringsn88keys** [comment]
@posco2k8, I've just started helping maintain this gem and have published a new version 0.8.1, which incorporates PR https://github.com/phatworx/devise_security_extension/pull/88
